name: CI - API Flash Sales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Executar testes
        run: npm test

      - name: Compilar TypeScript
        run: npm run build

      - name: Construir imagem Docker
        run: docker build -t api-flashsales:ci .